### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by bigZ-again** [legeneek/vue-image-clip#1]
在学Vue，正好需要做一个窗口裁剪的应用，看到了你的项目。
刚在看你的selectbox.vue，并未全部看完，有些想法：Vue的通过提供JS对象到DOM的数据绑定，来避免对DOM的直接修改，其实也就是应该要彻底替代JQuery。
你在实现drawRec方法时，是直接对DOM的style属性进行修改，为什么不用v-bind:style？我的建议是：
1、在template定义中嵌入 v-bind:style="myStyle"
2、定义computed属性myStyle，根据rec对象返回相应的值，主要是将数字转字符串并添加‘px’
这样的化，你的代码可以大大优化，如watch, drawRec都可以省去。
这里有我最近的一个[测试demo](http://share.weiyun.com/37a024ee8200af406779a8a163f8f10e)，供参考。
不论如何，谢谢你代码里的思路。

**Comment by legeneek** [comment]
多谢，能改进的地方蛮多的额...  
:style的方式个人不太习惯，一般样式修改都是改class实现，我这里也没有考虑太多
当时想把selectbox做的很干净的，只返回left,top,width,height 结果...
